param(
    [string]$ProjectPath = (Get-Location).Path
)

$ErrorActionPreference = "Stop"

$CodexHome = Join-Path $env:USERPROFILE ".codex"
$PresetDir = Join-Path $CodexHome "presets"
$McpPresetDir = Join-Path $PresetDir "mcp"
$BasePreset = Join-Path $PresetDir "base-project.toml"

$ProjectCodexDir = Join-Path $ProjectPath ".codex"
$ProjectConfig = Join-Path $ProjectCodexDir "config.toml"

function Set-Utf8NoBomContent {
    param(
        [Parameter(Mandatory=$true)][string]$Path,
        [Parameter(Mandatory=$true)][string]$Value
    )

    $encoding = [System.Text.UTF8Encoding]::new($false)
    [System.IO.File]::WriteAllText($Path, $Value, $encoding)
}

if (!(Test-Path $McpPresetDir)) {
    throw "Diretório de presets MCP não encontrado: $McpPresetDir"
}

$presets = Get-ChildItem $McpPresetDir -Filter "*.toml" | Sort-Object Name

Write-Host ""
Write-Host "MCP presets disponíveis:"
Write-Host ""

for ($i = 0; $i -lt $presets.Count; $i++) {
    Write-Host ("[{0}] {1}" -f ($i + 1), $presets[$i].BaseName)
}

Write-Host ""
Write-Host "Digite os números separados por vírgula. Ex: 1,3,4"
Write-Host "ENTER = nenhum MCP"
Write-Host ""

$inputRaw = Read-Host "Selecionar MCPs"

$selected = @()
$selectedNames = @()

if (![string]::IsNullOrWhiteSpace($inputRaw)) {
    $indexes = $inputRaw -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }

    foreach ($idx in $indexes) {
        if ($idx -notmatch "^\d+$") {
            throw "Índice inválido: $idx"
        }

        $n = [int]$idx

        if ($n -lt 1 -or $n -gt $presets.Count) {
            throw "Índice fora do intervalo: $n"
        }

        $preset = $presets[$n - 1]

        if ($selectedNames -notcontains $preset.BaseName) {
            $selected += $preset
            $selectedNames += $preset.BaseName
        }
    }
}

New-Item -ItemType Directory -Force -Path $ProjectCodexDir | Out-Null

if (Test-Path $ProjectConfig) {
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $backupPath = Join-Path $ProjectCodexDir "config.toml.bak-$timestamp"
    Copy-Item -LiteralPath $ProjectConfig -Destination $backupPath
}

$parts = New-Object System.Collections.Generic.List[string]

$parts.Add("# Generated by bootstrap-codex-project.ps1")
$parts.Add("# Project: $ProjectPath")
$parts.Add("")

if (Test-Path $BasePreset) {
    $parts.Add((Get-Content $BasePreset -Raw).Trim())
    $parts.Add("")
}

foreach ($preset in $selected) {
    $parts.Add("")
    $parts.Add("# --- MCP preset: $($preset.BaseName) ---")
    $parts.Add((Get-Content $preset.FullName -Raw).Trim())
}

$final = ($parts -join "`r`n").Trim() + "`r`n"

Set-Utf8NoBomContent -Path $ProjectConfig -Value $final

Write-Host ""
Write-Host "Config local criada:"
Write-Host $ProjectConfig

if ($selected.Count -gt 0) {
    Write-Host ""
    Write-Host "MCPs habilitados:"
    $selected | ForEach-Object { Write-Host "- $($_.BaseName)" }
}

$resolveScript = Join-Path $PSScriptRoot "resolve-codex-services.ps1"
$startServicesScript = Join-Path $PSScriptRoot "start-codex-services.ps1"

if ((Test-Path $resolveScript) -and (Test-Path $startServicesScript)) {
    $resolvedServices = @(& $resolveScript -McpNames $selectedNames -CodexHome $CodexHome)

    if ($resolvedServices.Count -gt 0) {
        Write-Host ""
        Write-Host "Serviços MCP resolvidos:"
        $resolvedServices | ForEach-Object { Write-Host "- $_" }

        & $startServicesScript -Services $resolvedServices -CodexHome $CodexHome
    }
}
